# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a549175bd1f8eb9652bb91227f9fd6da2a3adc4be839508821cc29a29308fc6eb3fab44bc6fd218529bdacde6039b5de538d1cd4a3cae4c737031bf1845d136

test:
  secret_key_base: ee5316ba1b246c7d957776debad7d6d64ddd48343de7b4e5d35c6d524b6176583b0ffa8df22e3ab843a1fbd75dec791f2e7ccba3337411a63f01000079f25fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
